services:
  - type: web
    name: analysis-of-pill
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn Detection_and_Analysis_of_Pill.wsgi:application --bind 0.0.0.0:$PORT --timeout 120 --workers 1"
